# This file is generated by setuptools_scm at build time.
# Do not edit manually.
#
# When building from a git tag, this will contain the exact
# released version (e.g. "0.6.0").
# On development branches, this will be a ".devN" version.

version = "0.0.0"
